---
- hosts: wordpress

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Install dependences
      ansible.builtin.apt:
        pkg:
          - apache2 
          - ghostscript 
          - libapache2-mod-php 
          - php 
          - php-bcmath 
          - php-curl 
          - php-imagick 
          - php-intl 
          - php-json 
          - php-mbstring 
          - php-xml 
          - php-zip
        update_cache: yes
        state: latest
      become: yes

    - name: Creating Directory
      ansible.builtin.file:
        path: /srv/www
        state: directory
        group: www-data
        owner: www-data
      become: yes

    - name: Download and unzip
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: true
      become: yes

    - name: Configuring Apache (seding file to server)
      ansible.builtin.copy:
        src: files/wordpress.conf
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - Restart apache

    - name: Copying sample configuration file
      ansible.builtin.copy:
        src: /srv/www/wordpress/wp-config-sample.php
        dest: /srv/www/wordpress/wp-config.php
        force: no
        remote_src: yes
      become: yes

    - name: Replacing with database informations
      ansible.builtin.replace:
        path: /srv/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
      - {regexp: "database_name_here", replace: "wordpress_db"}
      - {regexp: "username_here", replace: "wordpress_user"}
      - {regexp: "password_here", replace: "12345"}
      become: yes

    - name: Getting new salts from WordPress API
      ansible.builtin.uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: yes
      register: wp_salts

    - name: Configuring file to “known secrets” attacks
      ansible.builtin.replace:
        path: /home/arthur/testes/wordtesting.conf
        regexp: "(?s)define\\( 'AUTH_KEY'.*define\\( 'NONCE_SALT',\\s+'put your unique phrase here' \\);"
        replace: "{{ wp_salts.content }}"

    # - name: Configuring file to “known secrets” attacks
    #   ansible.builtin.lineinfile:
    #     path: /srv/www/wordpress/wp-config.php
    #     search_string: "{{ item.search_string }}"
    #     line: "{{ item.line }}"
    #   with_items:
    #   - {search_string: "define( 'AUTH_KEY',         'put your unique phrase here' );", line: "define('AUTH_KEY',         '+#X4]rw+3U6UNY!%|!:rR[3n%.+=<5CZ%{P$o?2K:&^ssU!dNJ|IN99rmdFfL&fV');"}
    #   - {search_string: "define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );", line: "define('SECURE_AUTH_KEY',  'Qp6Y)|=Bu%S>OmGjICAK!H+:{>)jJ13.p~IsW_k7hZ+l!ix%t!Tr,i-,!)e%(H.M');"}
    #   - {search_string: "define( 'LOGGED_IN_KEY',    'put your unique phrase here' );", line: "define('LOGGED_IN_KEY',    '^,lN=fW9<jS[&gBX#{YpuJH8&/&-6N1;!Op/bBXUA6/)$9;gbCWDi |:*?j51`la');"}
    #   - {search_string: "define( 'NONCE_KEY',        'put your unique phrase here' );", line: "define('NONCE_KEY',        '-(atC%a90 {47:?lP:nAY!Ugu?huf>mYz|6 &.MNuSv+=ko8ml>v9t|+e5wU2)d&');"}
    #   - {search_string: "define( 'AUTH_SALT',        'put your unique phrase here' );", line: "define('AUTH_SALT',        '|4_/wQ-]`c!ak7d.(3R2!))4,LiOARE({do0Sn>v.|SR;Oer.mHFFQ&!J_4C:2^)');"}
    #   - {search_string: "define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );", line: "define('SECURE_AUTH_SALT', '0Y!&;mT-XCk7i%bY~GAOVg04/l;Nf/EYsQX`pOcJtS}![fQIfgfR5IR^&743q T&');"}
    #   - {search_string: "define( 'LOGGED_IN_SALT',   'put your unique phrase here' );", line: "define('LOGGED_IN_SALT',   '4`JL_C;IvFFg>g|+04)a,A``=sY},f~ 1`;k2khLeM]BheXP._5-@_516(&W-1PB');"}
    #   - {search_string: "define( 'NONCE_SALT',       'put your unique phrase here' );", line: "define('NONCE_SALT',       'Nl(o.z22[tlRo@_:+9>kF%g|lY=;;W7Lic6!}3(N$?{NzYuC|(e^B5y31cso7#8+');"}
    #   become: yes
      
- hosts: mysql
  tasks:
    - name: Install dependences
      ansible.builtin.apt:
        pkg:
          - mysql-server 
          - python3-pymysql
        update_cache: yes
        state: latest
      become: yes

    - name: creating db (wordpress_db)
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: creating user (wordpress_user)
      community.mysql.mysql_user:
        name: wordpress_user
        password: 12345
        priv: "wordpress_db.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes



